############################# Wireshark - Network monitoring ############################
# wireshark - Network monitoring
# mkdir -p /volume1/docker/wireshark/config
# mkdir -p /volume1/docker/wireshark/captures
# https://mariushosting.com/how-to-install-wireshark-on-your-synology-nas/
##########################################################################################

version: "3.9"

services:
  wireshark:
    image: ghcr.io/linuxserver/wireshark
    container_name: wireshark
    hostname: TPE-DS920-Wireshark
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    labels:
      - org.hotio.pullio.update=${PULLIO_UPDATE}
      - org.hotio.pullio.notify=${PULLIO_NOTIFY}
      - org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - CUSTOM_USER=${CUSTOM_USER}
      - PASSWORD=${PASSWORD}
      - TZ=${TZ}
      - UMASK=002
    dns:
      - 1.1.1.1
      - 1.0.0.1
    env_file:
      - .env
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
    ports:
      - "3125:3001"
      - "3124:3000"
    volumes:
      - ${DOCKERCONFDIR}/config:/config
      - ${DOCKERCONFDIR}/captures:/captures
