version: "3.9"

services:
  wireshark:
    image: ghcr.io/linuxserver/wireshark
    container_name: wireshark
    restart: always
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "3125:3001"
      - "3124:3000"
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Bucharest
      - CUSTOM_USER=paeltc
      - PASSWORD=paeltc@hosting
    volumes:
      - /volume1/docker/wireshark/config:/config
      - /volume1/docker/wireshark/captures:/captures

      ## https://mariushosting.com/how-to-install-wireshark-on-your-synology-nas/
